BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE funcionario (
            id_funcionario NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            nome VARCHAR2(100) NOT NULL,
            cpf VARCHAR2(14) NOT NULL UNIQUE,
            cargo VARCHAR2(50) NOT NULL,
            telefone VARCHAR2(20) NOT NULL,
            email VARCHAR2(50) NOT NULL UNIQUE,
            senha VARCHAR2(255) NOT NULL,
            refresh_token VARCHAR2(255) DEFAULT NULL,
            expiracao_refresh_token TIMESTAMP DEFAULT NULL
        )
    ';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN -- -955 = ORA-00955 (tabela já existe)
            RAISE;
        END IF;
END;
/

INSERT INTO funcionario (nome, cpf, cargo, telefone, email, senha)
SELECT 'CONTA ADMIN', '00000000000', 'Admin', '00000000000', 'admin@email.com', '$2a$12$e6QJwFNdnau90pQN/3OkFeelAPVi8nCsJped.YQYxEy/573E1nR1G'
FROM dual
WHERE NOT EXISTS (SELECT 1 FROM funcionario WHERE email = 'admin@email.com');

INSERT INTO funcionario (nome, cpf, cargo, telefone, email, senha)
SELECT 'Joao Silva', '12345678900', 'Gerente', '11999990001', 'joao.silva@email.com', '$2a$12$P7BetbmT3nap8KkA/sD4aOHD8SI2JHSgkUrCuuzljXtd.wtpbEFHC'
FROM dual
WHERE NOT EXISTS (SELECT 1 FROM funcionario WHERE email = 'joao.silva@email.com');

INSERT INTO funcionario (nome, cpf, cargo, telefone, email, senha)
SELECT 'Maria Souza', '22345678900', 'Tecnico', '11999990002', 'maria.souza@email.com', '$2a$12$P7BetbmT3nap8KkA/sD4aOHD8SI2JHSgkUrCuuzljXtd.wtpbEFHC'
FROM dual
WHERE NOT EXISTS (SELECT 1 FROM funcionario WHERE email = 'maria.souza@email.com');

INSERT INTO funcionario (nome, cpf, cargo, telefone, email, senha)
SELECT 'Carlos Lima', '32345678900', 'Mecanico', '11999990003', 'carlos.lima@email.com', '$2a$12$P7BetbmT3nap8KkA/sD4aOHD8SI2JHSgkUrCuuzljXtd.wtpbEFHC'
FROM dual
WHERE NOT EXISTS (SELECT 1 FROM funcionario WHERE email = 'carlos.lima@email.com');

INSERT INTO funcionario (nome, cpf, cargo, telefone, email, senha)
SELECT 'Ana Costa', '42345678900', 'Supervisor', '11999990004', 'ana.costa@email.com', '$2a$12$P7BetbmT3nap8KkA/sD4aOHD8SI2JHSgkUrCuuzljXtd.wtpbEFHC'
FROM dual
WHERE NOT EXISTS (SELECT 1 FROM funcionario WHERE email = 'ana.costa@email.com');

COMMIT;
