CREATE TABLE funcionario (
    id_funcionario NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(100) NOT NULL,
    cpf VARCHAR2(14) NOT NULL UNIQUE,
    cargo VARCHAR2(50) NOT NULL,
    telefone VARCHAR2(20) NOT NULL,
    email VARCHAR2(50) NOT NULL UNIQUE,
    senha VARCHAR2(255) NOT NULL,
    refresh_token VARCHAR2(255) DEFAULT NULL,
    expiracao_refresh_token TIMESTAMP DEFAULT NULL
);

INSERT INTO funcionario (
    nome,
    cpf,
    cargo,
    telefone,
    email,
    senha,
    refresh_token,
    expiracao_refresh_token
) VALUES
('CONTA ADMIN', '000.000.000-00', 'ADMIN', '(00) 00000-0000', 'admin@email.com', 'adminmottu', NULL, NULL);

INSERT INTO funcionario (
    nome,
    cpf,
    cargo,
    telefone,
    email,
    senha,
    refresh_token,
    expiracao_refresh_token
) VALUES
('João Mecânico', '111.111.111-11', 'MECANICO', '(11) 11111-1111', 'joao@email.com', '$2a$12$WvSaeLKOeMhnaT65b1cHaeHQKyOz5M0cNDDNZ0eDbdmeLqoYbnFhi', NULL, NULL);

INSERT INTO funcionario (
    nome,
    cpf,
    cargo,
    telefone,
    email,
    senha,
    refresh_token,
    expiracao_refresh_token
) VALUES
('Maria Gerente', '222.222.222-22', 'GERENTE', '(22) 22222-2222', 'maria@email.com', '$2a$12$AymGyslp9tPClu/sIsfaNOVcAgUEdWXfrqG8liodWVIczQA9XYJ/e', NULL, NULL);