BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE patio (
            id_patio NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            nome VARCHAR2(100) NOT NULL,
            endereco VARCHAR2(200) NOT NULL,
            capacidade_maxima NUMBER NOT NULL
        )
    ';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN -- -955 = ORA-00955 (objeto já existe)
            RAISE;
        END IF;
END;
/

INSERT INTO patio (id_patio, nome, endereco, capacidade_maxima)
SELECT 1, 'Patio Central', 'Rua A 123', 50 FROM dual
WHERE NOT EXISTS (SELECT 1 FROM patio WHERE id_patio = 1);

INSERT INTO patio (id_patio, nome, endereco, capacidade_maxima)
SELECT 2, 'Patio Norte', 'Rua B 456', 30 FROM dual
WHERE NOT EXISTS (SELECT 1 FROM patio WHERE id_patio = 2);

INSERT INTO patio (id_patio, nome, endereco, capacidade_maxima)
SELECT 3, 'Patio Sul', 'Rua C 789', 40 FROM dual
WHERE NOT EXISTS (SELECT 1 FROM patio WHERE id_patio = 3);

INSERT INTO patio (id_patio, nome, endereco, capacidade_maxima)
SELECT 4, 'Patio Leste', 'Rua D 321', 20 FROM dual
WHERE NOT EXISTS (SELECT 1 FROM patio WHERE id_patio = 4);

INSERT INTO patio (id_patio, nome, endereco, capacidade_maxima)
SELECT 5, 'Patio Oeste', 'Rua E 654', 25 FROM dual
WHERE NOT EXISTS (SELECT 1 FROM patio WHERE id_patio = 5);

COMMIT;
