CREATE TABLE patio (
id_patio NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
nome VARCHAR2(100) NOT NULL,
endereco VARCHAR2(200) NOT NULL,
capacidade_maxima NUMBER NOT NULL
);

INSERT INTO patio (nome, endereco, capacidade_maxima) VALUES
('Patio Central', 'Rua Principal, 1000', 50);

INSERT INTO patio (nome, endereco, capacidade_maxima) VALUES
('Patio Norte', 'Av. Norte, 250', 30);

INSERT INTO patio (nome, endereco, capacidade_maxima) VALUES
('Patio Sul', 'Av. Sul, 500', 40);