CREATE TABLE moto (
id_moto NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
placa VARCHAR2(10) NOT NULL,
modelo VARCHAR2(50) NOT NULL,
fabricante VARCHAR2(50) NOT NULL,
ano NUMBER NOT NULL,
id_patio NUMBER NOT NULL,
localizacao_atual VARCHAR2(100) NOT NULL,
CONSTRAINT fk_moto_patio FOREIGN KEY (id_patio)
REFERENCES patio(id_patio)
);

INSERT INTO moto (placa, modelo, fabricante, ano, id_patio, localizacao_atual) VALUES
('ABC-1234', 'Mottu Pop', 'Honda', 2022, 1, 'Vaga 01');

INSERT INTO moto (placa, modelo, fabricante, ano, id_patio, localizacao_atual) VALUES
('DEF-5678', 'Mottu Sport', 'TVS', 2021, 1, 'Vaga 02');

INSERT INTO moto (placa, modelo, fabricante, ano, id_patio, localizacao_atual) VALUES
('GHI-9012', 'Mottu E', 'Yadea', 2023, 2, 'Vaga 01');

INSERT INTO moto (placa, modelo, fabricante, ano, id_patio, localizacao_atual) VALUES
('JKL-3456', 'Mottu Pop', 'Honda', 2022, 3, 'Vaga 03');
