BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE moto (
            id_moto NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            placa VARCHAR2(10) NOT NULL,
            modelo VARCHAR2(50) NOT NULL,
            fabricante VARCHAR2(50) NOT NULL,
            ano NUMBER NOT NULL,
            id_patio NUMBER NOT NULL,
            localizacao_atual VARCHAR2(100) NOT NULL,
            CONSTRAINT fk_moto_patio FOREIGN KEY (id_patio)
                REFERENCES patio(id_patio)
        )
    ';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

INSERT INTO moto (id_moto, placa, modelo, fabricante, ano, id_patio, localizacao_atual)
SELECT 1, 'ABC1234', 'Mottu Pop', 'Honda', 2020, 1, 'Rua A' FROM dual
WHERE NOT EXISTS (SELECT 1 FROM moto WHERE id_moto = 1);

INSERT INTO moto (id_moto, placa, modelo, fabricante, ano, id_patio, localizacao_atual)
SELECT 2, 'DEF5678', 'Mottu Sport', 'TVS', 2021, 2, 'Rua B' FROM dual
WHERE NOT EXISTS (SELECT 1 FROM moto WHERE id_moto = 2);

INSERT INTO moto (id_moto, placa, modelo, fabricante, ano, id_patio, localizacao_atual)
SELECT 3, 'GHI9012', 'Mottu E', 'Yadea', 2019, 3, 'Rua C' FROM dual
WHERE NOT EXISTS (SELECT 1 FROM moto WHERE id_moto = 3);

INSERT INTO moto (id_moto, placa, modelo, fabricante, ano, id_patio, localizacao_atual)
SELECT 4, 'JKL3456', 'Mottu Pop', 'Honda', 2022, 4, 'Rua D' FROM dual
WHERE NOT EXISTS (SELECT 1 FROM moto WHERE id_moto = 4);

INSERT INTO moto (id_moto, placa, modelo, fabricante, ano, id_patio, localizacao_atual)
SELECT 5, 'MNO7890', 'Mottu Pop', 'Honda', 2023, 5, 'Rua E' FROM dual
WHERE NOT EXISTS (SELECT 1 FROM moto WHERE id_moto = 5);

COMMIT;
