CREATE TABLE camera (
id_camera NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
status_operacional VARCHAR2(20) NOT NULL,
localizacao_fisica VARCHAR2(255) NOT NULL,
id_patio NUMBER NOT NULL,
CONSTRAINT fk_camera_patio FOREIGN KEY (id_patio)
REFERENCES patio(id_patio)
);

INSERT INTO camera (status_operacional, localizacao_fisica, id_patio) VALUES
('OPERACIONAL', 'Entrada principal', 1);

INSERT INTO camera (status_operacional, localizacao_fisica, id_patio) VALUES
('OPERACIONAL', 'Saída norte', 1);

INSERT INTO camera (status_operacional, localizacao_fisica, id_patio) VALUES
('MANUTENCAO', 'Corredor lateral', 2);

INSERT INTO camera (status_operacional, localizacao_fisica, id_patio) VALUES
('OPERACIONAL', 'Entrada sul', 3);
