BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE camera (
            id_camera NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            status_operacional VARCHAR2(20) NOT NULL,
            localizacao_fisica VARCHAR2(255) NOT NULL,
            id_patio NUMBER NOT NULL,
            CONSTRAINT fk_camera_patio FOREIGN KEY (id_patio)
                REFERENCES patio(id_patio)
        )
    ';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

INSERT INTO camera (id_camera, status_operacional, localizacao_fisica, id_patio)
SELECT 1, 'Operacional', 'Entrada Patio Central', 1 FROM dual
WHERE NOT EXISTS (SELECT 1 FROM camera WHERE id_camera = 1);

INSERT INTO camera (id_camera, status_operacional, localizacao_fisica, id_patio)
SELECT 2, 'Manutencao', 'Saida Patio Norte', 2 FROM dual
WHERE NOT EXISTS (SELECT 1 FROM camera WHERE id_camera = 2);

INSERT INTO camera (id_camera, status_operacional, localizacao_fisica, id_patio)
SELECT 3, 'Operacional', 'Corredor Patio Sul', 3 FROM dual
WHERE NOT EXISTS (SELECT 1 FROM camera WHERE id_camera = 3);

INSERT INTO camera (id_camera, status_operacional, localizacao_fisica, id_patio)
SELECT 4, 'Inoperante', 'Portao Patio Leste', 4 FROM dual
WHERE NOT EXISTS (SELECT 1 FROM camera WHERE id_camera = 4);

INSERT INTO camera (id_camera, status_operacional, localizacao_fisica, id_patio)
SELECT 5, 'Operacional', 'Garagem Patio Oeste', 5 FROM dual
WHERE NOT EXISTS (SELECT 1 FROM camera WHERE id_camera = 5);

COMMIT;
