BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE aruco_tag (
            id_tag NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            codigo VARCHAR2(50) NOT NULL,
            status VARCHAR2(20) NOT NULL,
            id_moto NUMBER NOT NULL,
            CONSTRAINT fk_aruco_moto FOREIGN KEY (id_moto)
                REFERENCES moto(id_moto)
        )
    ';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

INSERT INTO aruco_tag (id_tag, codigo, status, id_moto)
SELECT 1, 'TAG001', 'Ativo', 1 FROM dual
WHERE NOT EXISTS (SELECT 1 FROM aruco_tag WHERE id_tag = 1);

INSERT INTO aruco_tag (id_tag, codigo, status, id_moto)
SELECT 2, 'TAG002', 'Ativo', 2 FROM dual
WHERE NOT EXISTS (SELECT 1 FROM aruco_tag WHERE id_tag = 2);

INSERT INTO aruco_tag (id_tag, codigo, status, id_moto)
SELECT 3, 'TAG003', 'Inativo', 3 FROM dual
WHERE NOT EXISTS (SELECT 1 FROM aruco_tag WHERE id_tag = 3);

INSERT INTO aruco_tag (id_tag, codigo, status, id_moto)
SELECT 4, 'TAG004', 'Ativo', 4 FROM dual
WHERE NOT EXISTS (SELECT 1 FROM aruco_tag WHERE id_tag = 4);

INSERT INTO aruco_tag (id_tag, codigo, status, id_moto)
SELECT 5, 'TAG005', 'Manutencao', 5 FROM dual
WHERE NOT EXISTS (SELECT 1 FROM aruco_tag WHERE id_tag = 5);

COMMIT;
