CREATE TABLE aruco_tag (
id_tag NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
codigo VARCHAR2(50) NOT NULL,
status VARCHAR2(20) NOT NULL,
id_moto NUMBER NOT NULL,
CONSTRAINT fk_aruco_moto FOREIGN KEY (id_moto)
REFERENCES moto(id_moto)
);

INSERT INTO aruco_tag (codigo, status, id_moto) VALUES ('TAG001', 'ATIVO', 1);
INSERT INTO aruco_tag (codigo, status, id_moto) VALUES ('TAG002', 'ATIVO', 2);
INSERT INTO aruco_tag (codigo, status, id_moto) VALUES ('TAG003', 'INATIVO', 3);
INSERT INTO aruco_tag (codigo, status, id_moto) VALUES ('TAG004', 'ATIVO', 4);
