CREATE TABLE localidade (
id_localidade NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
data_hora TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
ponto_referencia VARCHAR2(100) NOT NULL,
id_moto NUMBER NOT NULL,
id_patio NUMBER NOT NULL,
id_camera NUMBER NOT NULL,
CONSTRAINT fk_local_moto FOREIGN KEY (id_moto) REFERENCES moto(id_moto),
CONSTRAINT fk_local_patio FOREIGN KEY (id_patio) REFERENCES patio(id_patio),
CONSTRAINT fk_local_camera FOREIGN KEY (id_camera) REFERENCES camera(id_camera)
);

INSERT INTO localidade (ponto_referencia, id_moto, id_patio, id_camera) VALUES ('Entrada principal', 1, 1, 1);
INSERT INTO localidade (ponto_referencia, id_moto, id_patio, id_camera) VALUES ('Saída norte', 2, 1, 2);
INSERT INTO localidade (ponto_referencia, id_moto, id_patio, id_camera) VALUES ('Corredor lateral', 3, 2, 3);
INSERT INTO localidade (ponto_referencia, id_moto, id_patio, id_camera) VALUES ('Vaga sul', 4, 3, 4);
