BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE localidade (
            id_localidade NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            data_hora TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
            ponto_referencia VARCHAR2(100) NOT NULL,
            id_moto NUMBER NOT NULL,
            id_patio NUMBER NOT NULL,
            id_camera NUMBER NOT NULL,
            CONSTRAINT fk_local_moto FOREIGN KEY (id_moto) REFERENCES moto(id_moto),
            CONSTRAINT fk_local_patio FOREIGN KEY (id_patio) REFERENCES patio(id_patio),
            CONSTRAINT fk_local_camera FOREIGN KEY (id_camera) REFERENCES camera(id_camera)
        )
    ';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

INSERT INTO localidade (id_localidade, data_hora, ponto_referencia, id_moto, id_patio, id_camera)
SELECT 1, TIMESTAMP '2025-11-01 08:00:00', 'Portao A', 1, 1, 1 FROM dual
WHERE NOT EXISTS (SELECT 1 FROM localidade WHERE id_localidade = 1);

INSERT INTO localidade (id_localidade, data_hora, ponto_referencia, id_moto, id_patio, id_camera)
SELECT 2, TIMESTAMP '2025-11-01 08:10:00', 'Portao B', 2, 2, 2 FROM dual
WHERE NOT EXISTS (SELECT 1 FROM localidade WHERE id_localidade = 2);

INSERT INTO localidade (id_localidade, data_hora, ponto_referencia, id_moto, id_patio, id_camera)
SELECT 3, TIMESTAMP '2025-11-01 08:20:00', 'Portao C', 3, 3, 3 FROM dual
WHERE NOT EXISTS (SELECT 1 FROM localidade WHERE id_localidade = 3);

INSERT INTO localidade (id_localidade, data_hora, ponto_referencia, id_moto, id_patio, id_camera)
SELECT 4, TIMESTAMP '2025-11-01 08:30:00', 'Portao D', 4, 4, 4 FROM dual
WHERE NOT EXISTS (SELECT 1 FROM localidade WHERE id_localidade = 4);

INSERT INTO localidade (id_localidade, data_hora, ponto_referencia, id_moto, id_patio, id_camera)
SELECT 5, TIMESTAMP '2025-11-01 08:40:00', 'Portao E', 5, 5, 5 FROM dual
WHERE NOT EXISTS (SELECT 1 FROM localidade WHERE id_localidade = 5);

COMMIT;
