BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE registro_status (
            id_status NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            tipo_status VARCHAR2(50) NOT NULL,
            descricao VARCHAR2(255),
            data_status TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            id_moto NUMBER NOT NULL,
            id_funcionario NUMBER NOT NULL,
            CONSTRAINT fk_moto_status FOREIGN KEY (id_moto) REFERENCES moto(id_moto),
            CONSTRAINT fk_funcionario_status FOREIGN KEY (id_funcionario) REFERENCES funcionario(id_funcionario)
        )
    ';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

INSERT INTO registro_status (id_status, tipo_status, descricao, id_moto, id_funcionario)
SELECT 1, 'DISPONIVEL', 'Moto pronta para uso', 1, 1 FROM dual
WHERE NOT EXISTS (SELECT 1 FROM registro_status WHERE id_status = 1);

INSERT INTO registro_status (id_status, tipo_status, descricao, id_moto, id_funcionario)
SELECT 2, 'MANUTENCAO', 'Aguardando documentacao.', 2, 3 FROM dual
WHERE NOT EXISTS (SELECT 1 FROM registro_status WHERE id_status = 2);

INSERT INTO registro_status (id_status, tipo_status, descricao, id_moto, id_funcionario)
SELECT 3, 'MANUTENCAO', 'Revisao geral.', 3, 2 FROM dual
WHERE NOT EXISTS (SELECT 1 FROM registro_status WHERE id_status = 3);

INSERT INTO registro_status (id_status, tipo_status, descricao, id_moto, id_funcionario)
SELECT 4, 'RESERVADO', 'Reservada via app.', 4, 4 FROM dual
WHERE NOT EXISTS (SELECT 1 FROM registro_status WHERE id_status = 4);

INSERT INTO registro_status (id_status, tipo_status, descricao, id_moto, id_funcionario)
SELECT 5, 'BAIXA_BOLETIM_OCORRENCIA', 'Moto furtada.', 5, 1 FROM dual
WHERE NOT EXISTS (SELECT 1 FROM registro_status WHERE id_status = 5);

COMMIT;
