CREATE TABLE registro_status (
    id_status NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_status VARCHAR2(50) NOT NULL,
    descricao VARCHAR2(255),
    data_status TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    id_moto NUMBER NOT NULL,
    id_funcionario NUMBER NOT NULL,
    CONSTRAINT fk_moto_status FOREIGN KEY (id_moto) REFERENCES moto(id_moto),
    CONSTRAINT fk_funcionario_status FOREIGN KEY (id_funcionario) REFERENCES funcionario(id_funcionario)
);

INSERT INTO registro_status (tipo_status, descricao, id_moto, id_funcionario)
VALUES ('DISPONIVEL', 'Moto pronta para uso', 1, 1);

INSERT INTO registro_status (tipo_status, descricao, id_moto, id_funcionario)
VALUES ('MANUTENCAO', 'Troca de óleo', 2, 2);

INSERT INTO registro_status (tipo_status, descricao, id_moto, id_funcionario)
VALUES ('RESERVADO', 'Reservada para cliente', 3, 2);

INSERT INTO registro_status (tipo_status, descricao, id_moto, id_funcionario)
VALUES ('BAIXA_BOLETIM_OCORRENCIA', 'Perda por BO', 4, 1);

